# Generated by Django 5.2.16 on 2026-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='send_duration_days',
            field=models.IntegerField(blank=True, help_text='Duração em dias para enviar mensagens. Null = indeterminado.', null=True),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='send_times',
            field=models.JSONField(default=list, help_text='Horários de disparo. Ex: ["08:00", "14:00", "20:00"]'),
        ),
    ]
