# Generated by Django 5.2.16 on 2026-07-29 20:28

import scraper_bot.skills.extractors.registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_bot', '0005_executionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='site_type',
            field=models.CharField(choices=scraper_bot.skills.extractors.registry.list_site_choices, default='aluno_presente', help_text='Tipo do site alvo para selecionar o extrator apropriado', max_length=50),
        ),
    ]
