# Generated by Django 5.2.16 on 2026-07-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno_presente_sme', '0002_botconfig_send_duration_days_botconfig_send_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template de mensagem usado no disparo automático', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluno_presente_sme.messagetemplate'),
        ),
    ]
