# Generated by Django 5.2.16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno_presente_sme', '0003_add_template_to_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='send_days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='Dias da semana para disparo. 0=segunda, 6=domingo. Vazio = todos os dias.'),
        ),
    ]
