# Generated by Django 5.2.16 on 2026-07-29 20:28

import aluno_presente_sme.skills.extractors.registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno_presente_sme', '0005_executionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='site_type',
            field=models.CharField(choices=aluno_presente_sme.skills.extractors.registry.list_site_choices, default='aluno_presente', help_text='Tipo do site alvo para selecionar o extrator apropriado', max_length=50),
        ),
    ]
