# Generated by Django 5.2.16 on 2026-08-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno_presente_sme', '0006_add_site_type_to_botconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='school_unit_ids',
            field=models.JSONField(blank=True, default=list, help_text='IDs das unidades escolares da API para filtrar. Vazio = todas as unidades.'),
        ),
    ]
