# Generated by Django 5.2.16 on 2026-08-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno_presente_sme', '0007_add_school_unit_ids_to_botconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(help_text='ID da unidade escolar na API Aluno Presente')),
                ('unit_name', models.CharField(help_text='Nome da unidade escolar', max_length=255)),
                ('period', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('INTEGRAL', 'Integral'), ('NOTURNO', 'Noturno')], help_text='Período de funcionamento da unidade', max_length=20)),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Última sincronização com o dashboard')),
            ],
            options={
                'verbose_name': 'Período da Unidade',
                'verbose_name_plural': 'Períodos das Unidades',
                'ordering': ['period', 'unit_name'],
                'unique_together': {('unit_id', 'period')},
            },
        ),
    ]
