# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno_presente_sme', '0008_add_unitperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='cpf',
            field=models.CharField(
                blank=True,
                default='',
                help_text='CPF do destinatário (formato: XXX.XXX.XXX-XX)',
                max_length=14,
            ),
        ),
        migrations.AddField(
            model_name='recipient',
            name='matricula_funcional',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Matrícula funcional do destinatário',
                max_length=50,
            ),
        ),
    ]
